//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_cơ_sở.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiLam
    {
        public int MaBL { get; set; }
        public Nullable<int> MaCH { get; set; }
        public string MSSV { get; set; }
        public Nullable<int> MaDT { get; set; }
        public string DeBai { get; set; }
        public string CauA { get; set; }
        public string CauB { get; set; }
        public string CauC { get; set; }
        public string CauD { get; set; }
        public string DapAn { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
    }
}
