//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_cơ_sở.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeThi()
        {
            this.DeThi_CauHoi = new HashSet<DeThi_CauHoi>();
            this.DeThi_SInhVien = new HashSet<DeThi_SInhVien>();
            this.Diems = new HashSet<Diem>();
        }
    
        public int MaDT { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public Nullable<int> ThoiGianThi { get; set; }
        public Nullable<int> SoLuongCauHoi { get; set; }
        public Nullable<int> MaMH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeThi_CauHoi> DeThi_CauHoi { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeThi_SInhVien> DeThi_SInhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem> Diems { get; set; }
    }
}
