//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_cơ_sở.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public string MaGV { get; set; }
        public string HoTen { get; set; }
        public string email { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<int> MaQuyen { get; set; }
        public Nullable<int> MaMH { get; set; }
        public string GioiTinh { get; set; }
        public string QueQuan { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual Quyen Quyen { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
