//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án_cơ_sở.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.DeThi_SInhVien = new HashSet<DeThi_SInhVien>();
            this.Diems = new HashSet<Diem>();
        }
    
        public string MSSV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySInh { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<int> MaQuyen { get; set; }
        public Nullable<int> DTdanglam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeThi_SInhVien> DeThi_SInhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem> Diems { get; set; }
        public virtual Quyen Quyen { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
